config/routes.rb
CSSAInfoplatform::Application.routes.draw do

  resources :users do
    member do
      get 'publichome'# inbox
      get 'profile'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :update, :destroy]
  
  resources :groups, only: [:create, :destroy]
  
  resources :replies, only: [:create, :destroy]

  root :to => 'home_page#home'
  match '/help', to: 'static_page#help'
  match '/home', to: 'home_page#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/allinfo', to: 'users#allinfo'
  match '/allgroup', to: 'users#allgroup'
  match '/post', to: 'users#post'

end

app/views/shared/_feed.html.erb
<% cache(@feed_items) do %>
	<% if @feed_items.any? %>
		<ol class="microposts">
			<%= render partial: 'shared/feed_item', collection: @feed_items %>
		</ol>
	<% end %>
<% end %>

app/views/shared/_feed_item.html.erb
<li class="feed_item decorate_p" id="<%= feed_item.id %>">
	<% cache(feed_item) do %>
		<span class="users">
			<%= link_to gravatar_for(feed_item.user), feed_item.user %>
			<%= link_to feed_item.user.name,  publichome_user_path(feed_item.user) %>
		</span>
		<span class="feed_group">[Group: <%= feed_item.group_name %>]</span>
		<sapn class="feed_title">[Title: <%= feed_item.title %>]</span>	
		<sapn class="feed_content">[Content: <%= feed_item.content %>]</span>
	<% end %>
	<span class="timestamp timestamp_grey">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user)%>
		<%= link_to "delete", feed_item, method: :delete, confirm: "You sure?", title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f|%>
	<%= render 'error/error_messages', object: @micropost%>
	
	<div class="filed">
		<%= f.text_area :title, placeholder: "Compose new title", class: "compose_title" %>
		<%= f.text_area :content, placeholder: "Compose new micropost", class: "compose_content" %>
	    <!--<%= f.label :group_id %>-->	    
		<!-- <%= f.text_area :group_name, placeholder: "Add the group" %> -->
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary btn_compose" %>
	
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user)%>">
	<%= gravatar_for current_user%>
</a>
<h2><%= current_user.name %></h2>