config/routes.rb
CSSAInfoplatform::Application.routes.draw do

  resources :users do
    member do
      get 'publichome'# inbox
      get 'profile'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :update, :destroy]
  
  resources :groups, only: [:create, :destroy]
  
  resources :replies, only: [:create, :destroy]

  root :to => 'home_page#home'
  match '/help', to: 'static_page#help'
  match '/home', to: 'home_page#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  match '/allinfo', to: 'users#allinfo'
  match '/allgroup', to: 'users#allgroup'
  match '/post', to: 'users#post'

end

app/views/layouts/_footer.html.erb
<footer class = "navbar navbar-fixed-bottom footer">
    
    <span>
    	<li><a href="https://groups.google.com/forum/#!forum/ucsb-cssa">UCSB CSSA GOOGLE GROUP</a></li>
    </span>
    <span>
    	<li><a href=" http://www.ucsbcssa.org/">UCSB CSSA HOME</a></li>
    </span>    
    <span class = "contact_us"> <%= link_to "Contact Us", '#' %></span>  
    <span class = "version">
      InfoPlatform V1.0.0 by team6_CS290
    </span>
   
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
	<div class="collapse navbar-collapse">
		<div class="container">
			<%if not signed_in? %>
			<%= link_to image_tag("logo.jpg"), '/home', id: "logo" %>
			<%else %>
			<%= link_to image_tag("logo.jpg"), current_user, id: "logo" %>
			<%end %>
			<ul class="nav navbar-nav navbar-right">
				<%if not signed_in? %>
				<li>
					<%= link_to "Home", root_path%>
				</li>
				<li>
					<%= link_to "Sign in",signin_path %>
				</li>
				<%else %>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#"> My Profile <span class="caret"></span> </a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Private", current_user%>
						</li>
						<li>
							<%= link_to "Public", publichome_user_path(current_user)%>
						</li>
					</ul>
				</li>

				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#"> All Information <span class="caret"></span> </a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "Posts", allinfo_path %>
						</li>
						<li>
							<%= link_to "Users", users_path %>
						</li>
						<li>
							<%= link_to "Groups", allgroup_path %>
						</li>
					</ul>
				</li>

				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#"> Settings <span class="caret"></span> </a>

					<ul class="dropdown-menu">
						<li>
							<%= link_to "Profile", profile_user_path(current_user) %>
						</li>
						<li>
							<%= link_to "Account", edit_user_path(current_user) %>
						</li>
					</ul>
				</li>
				<li>
					<%= link_to "Sign Out", signout_path, method: "delete"%>
				</li>
				<%end %>
				<li>
					<%= link_to "Help", '/help'%>
				</li>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>CSSA_Infoplatform</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="content">
    <div class="container">
      <% flash.each do |key, value|%>
        <div class = "alert alert-<%= key %>"><%= value %></div>
      <%end%>
      <%= yield %>
    </div>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>